### ISSUE TITLE
Monitor Sufia for updates to fix LDP::Gone issue

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1137]
Also - consolidate all pins in Gemfile with notes about when to remove them

**Comment by jamesvanmil** [comment]
This issue is blocked by Sufia 7.2 requirement for hydra-head to 10.4.0

Per aufia issue https://github.com/projecthydra/sufia/issues/3065, active-fedora fixes the LDP::Gone problem.

We need to wait for the active_fedora fix to filter into Sufia, then re-pin sufia to a current commit.

Changed title from: Pin hydra-head to 10.3.0

**Comment by hortongn** [comment]
Reopened https://github.com/projecthydra/sufia/issues/3065 because this bug still exists

**Comment by hortongn** [comment]
@newmanld I verified that https://github.com/projecthydra/active_fedora/pull/1209 fixes the LDP::Gone error.  So I'm closing this since we'll have the fix once a new version of Active Fedora is cut.

If anyone wants to force their local app to use this fix, just edit your Gemfile to use the GitHub master branch version of Active Fedora instead of the published version of the gem.
