### ISSUE TITLE
Citation :  Needs to be singular.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1160]
### Descriptive summary

The citation field is multi-valued and needs to be set as singular for all work types.

**Comment by crowesn** [comment]
I think we had a discussion about removing this field since Sufia comes with functionality to generate citations on the fly: 
<img width="426" alt="screen shot 2017-03-10 at 8 29 23 am" src="https://cloud.githubusercontent.com/assets/1069588/23797011/c8f612fc-056b-11e7-9f00-0a2d40ff3dfd.png">

Closing this and making issue to remove :bibliographic_citation from the form.

**Comment by scherztc** [comment]
Size: 2
