### ISSUE TITLE
Set catalog display of works to only show certain fields.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1179]
### Descriptive summary

I want to have consistent metadata labels in the catalog views of works and collections.

### Expected behavior

When the metadata profile was migrated to Scholar 3, I overly included too may fields on the catalog display of works.  This needs to trimmed down to the same fields displayed in Scholar 2.x

**Comment by crowesn** [comment]
In curate/scholar 2 shows the following fields per object on the catalog index.

#### Works (all types)
* title
* creator
* description

#### Collections
* title
* description
* *owner*

In Sufia/scholar3, field display for catalog index is set globally for all types (works and collections) in ```app/controllers/catalog_controller.rb```. 

If we display owners (:depositor), the field will show not just for collections but also works.
Currently in scholar 3, collections can have a :creator, but this isn't a required field and is not available to collections in scholar 2.

I reached out to the POs and they said they prefer for collections to display owner(:depositor) on the catalog index but that it was not a priority for beta release. Since this will require some deeper development, I'll create a new issue for collections owner display and submit a PR satisfying #1179.
