### ISSUE TITLE
Batch create forms using Curation Concerns defaults

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1252]
The batch create form for articles at /batch_uploads/new?payload_concern=Article#metadata uses the `Creator` label on one of the metadata fields instead of `Author`

**Comment by jamesvanmil** [comment]
This problem is broader - the batch create is using a transient object type called `BatchUploadItem` which uses all of the Curation Concerns default form attritubes, translating them to the object specified by the `payload_concern` param after the form is submitted.

So all batch create forms are using the Curation Concern defaults, not our local attribute profiles.

Editing title to of the issue reflect this.

**Comment by jamesvanmil** [comment]
I don't think we're going to be able to tackle this without forking Sufia, or without an alarming number of overrides - I've marked as blocked for now, pending further discussion.

**Comment by crowesn** [comment]
We swarmed on this and consensus approach is to identify a base set of common fields for all work types and customize the batch upload form to show that limited set. Labels will be generalized, e.g. "abstract/description."
Will confer with metadata SME on appropriate fields/labels.

**Comment by crowesn** [comment]
Closed in favor of https://github.com/uclibs/scholar_uc/issues/1214
