### ISSUE TITLE
Existing DOI field not validated

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc#1390]
### Descriptive summary

The DOI form partial includes an option to add an existing DOI but lacks validation. We've discovered some user input with full urls, resulting in a broken link in the show view.

There is no validation on the field; it expects a clean doi with no protocol. The show view constructs a URL from the user input regardless of the contents. 

### Expected behavior

User input with not-well-formed doi should fail validation e.g.
`bad-nonsens-doi`
`http://dx.doi.org...`

### Actual behavior

Input is accepted and concatenated into a doi url on the show view e.g. 
> http://dx.doi.org/bad-nonsens-doi
> http://dx.doi.org/http://dx.doi.org...

### Related work

https://github.com/uclibs/scholar_uc/issues/1389

**Comment by newmanld** [comment]
See https://github.com/uclibs/scholar_uc/issues/1389

**Comment by newmanld** [comment]
I think we need not only validation, but, if feasible, the ability for content submitters to edit (change or remove) an external DOI, while not allowing them to change or remove (without deleting the work) a DOI minted from within Scholar@UC.

**Comment by newmanld** [comment]
Could require two DOI fields, to separate minted from external DOIs?  None of the handshakes (what happens when a work comes out of Embargo or Private status with a reserved DOI, or withdrawing a work) apply to external DOIs.   External DOIs could/should be treated more as a related URL, with the ability of the submitter/editor to change if they got it wrong.  (Possibly run this by P.O.s.)

**Comment by jamesvanmil** [comment]
@newmanld please open a new issue if you'd like that enhancement

**Comment by newmanld** [comment]
@jamesvanmil I'd like some discussion here within the context of what Kyle is already working on, and then yes I will write up as a new issue, and/or modify this issue.
