### ISSUE TITLE
The "Batch create" link on new work forms is broken

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#1410]
Reported by Amy Koshoffer:

_Not sure if this is underdevelopment still but I got this error when I click on batch upload from add dataset worktype.  I do not see this if I use the upper right works menu > batch create._

Note: This is the link you find on the Metadata tab of a new work form.  Just under the tab where it says "To create a separate work for each of the files, go to Batch upload"

![image001](https://cloud.githubusercontent.com/assets/5639859/26220784/ff93c3fc-3be1-11e7-95d1-67dbd51d64b5.png)

**Comment by newmanld** [comment]
This appears to me to be an error for each work type - from the individual input form - from the instruction at the top that says "To create a separate work for each of the files, go to Batch upload."  It looks like the link needs to be extended with the right qualifier.  For example, if you are on the dataset work type and click on this link, instead of going to  /batch_uploads/new, go to /batch_uploads/new?payload_concern=Dataset

**Comment by hortongn** [comment]
@13miciunasl To fix this, copy `app/views/hyrax/base/_form.html.erb` from Hyrax and edit

`<%= link_to "Batch upload", hyrax.new_batch_upload_path %>`
to be
`<%= link_to "Batch upload", "#{hyrax.new_batch_upload_path}&payload_concern=#{@form.model.class}" %>`
