### ISSUE TITLE
Change label on Collections - Add existing works

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1451]
### Descriptive summary

Change label from Add works to Add existing works.

This is from the Collection Show page.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by newmanld** [comment]
See https://github.com/samvera/hyrax/issues/1200#issuecomment-307890569

**Comment by newmanld** [comment]
This issue was motivated by this Beta feedback "This maybe isn't a bug but more of a UI question: I successfully created a new Collection, then I clicked "Add Works" which I expected to take me to the "New Work" page so I could upload and instead took me to the "My Works" page, which doesn't have any upload links/options."
