### ISSUE TITLE
Ex-proxy users still able to edit works after being removed as proxy

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#1665]
After removing a user as a proxy, that user still retains edit access to works they deposited as a proxy.

**Comment by flutterflies** [comment]
This is happening because once a proxy user submits a work on behalf that user is added as an editor to the work. 
![image](https://user-images.githubusercontent.com/12132647/31097093-21b1115e-a78c-11e7-9b38-771292a65508.png)

Users can still be removed individually from works but they are not removed at the same time they are removed as a proxy. 

The only way I think we can remove this at the same time the proxy user is removed would be to loop through every work owned by that user and remove the proxy user and an editor, however, that doesn't seem very practical and might cause unwanted effects
