### ISSUE TITLE
Investigate Solr relevance manipulation

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1778]
Target for after Hyrax 2.x (post-collection-extension)

Figure out how to boost the relevancy of collections, so that, for example, when you search for a simple keyword, a collection will appear in the results before the items within the collection.

**Comment by jayanthdeejay** [comment]
Note to self: Blacklight + Solr

**Comment by jayanthdeejay** [comment]
Notes:

There are two ways to fine tune search relevancy.
* **at index time:** change the priority of various fields during indexing, i.e., as and when a new work is added, various fields (title, description, file type, file title etc...) in that particular work can be given higher/lower boost values depending on how we want the search results. For the existing works, we have to reindex to reflect the changes in boost values so that both new works and existing works are on the same page in terms of search relevancy.
* **at query time:** we can modify the solr search query dynamically at query time by increasing the boost values of various fields like above. In this case, there is no need for reindexing.

**Comment by jayanthdeejay** [comment]
Search fine tuning can be done in our application in solrconfig.xml, specifically https://github.com/uclibs/scholar_uc/blob/2fecf19ddebf79ab4ed6491732c97b1540d835fe/solr/config/solrconfig.xml#L84-L152

**Comment by jayanthdeejay** [comment]
https://lucene.apache.org/solr/guide/6_6/learning-to-rank.html
