### ISSUE TITLE
Missing images on a help page

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1873]
### Descriptive summary

This page includes several images, and two are missing.  https://scholar.uc.edu/student_instructions?locale=en

### Actual behavior
The missing images are: 
https://scholar.uc.edu/assets/scholar_screens/add_file_image.png
https://scholar.uc.edu/assets/scholar_screens/content_editors_image.png

See also #1871

**Comment by scherztc** [comment]
@hortongn The images are on Scholar-dev:  https://scholar-dev.uc.edu/student_instructions?locale=en.  Not sure what would be different on Production and QA?

**Comment by hortongn** [comment]
@flutterflies or whomever is taking on this issue: 

I believe these images are broken in `production` mode because we are hard-coding the HTML image tag (`<img...`) instead of properly accessing the asset pipeline with `img_tag`. 

Replace the two broken image tags in the document with something like:
`<%= image_tag 'scholar_screens/something.png', alt: 'the alt text', title: 'the title text' %>`

If you can get the images to display in `development` mode using `img_tag`, I'm confident they will display properly in `production` mode too.  We can test the solution on scholar-qa.

**Comment by hortongn** [comment]
@flutterflies since you are out until Wednesday, I'm going ahead and reassigning this to @changy66 for her to work on now.
