### ISSUE TITLE
Department Names with ampersands breaking facet search

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1926]
### Descriptive summary

On a work show page, Department names are a faceted search.  Department names that include an ampersand are failing.

### Expected behavior
The search should retrieve all works with the same Department.

### Actual behavior
No works are found.

### Steps to reproduce the behavior

1. Go to this work: https://scholar.uc.edu/show/bc386p00p
1. Click, beside Department, on Digital Collections & Repositories 

No results will be found.  Department links, on work show pages, with other Departments with an ampersand in the name, which are similarly failing.  Department links on work show pages, without an ampersand in the department name, do not fail.  

The faceted browse works (from the Catalog, selecting the College, then the Department).

**Comment by hortongn** [comment]
In Linda's example above, the link that is currently generated for Department is
`https://scholar.uc.edu/catalog?f%5Bdepartment_sim%5D%5B%5D=Digital+Collections+%26amp%3B+Repositories`

The way it should be for Solr to properly find works with that department is
`https://scholar.uc.edu/catalog?f%5Bdepartment_sim%5D%5B%5D=Digital+Collections+%26+Repositories`

So when ampersands are used, they should be encoded as `%26` instead of `%26amp%3B`
