### ISSUE TITLE
Research splitting the user's first and last name into separate fields

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#234]
Contingent on the Metadata Working Group's recommendations

**Comment by jamesvanmil** [comment]
Issues notes:

* We should retain natural order of the name display in all display scenarios. The only exception is on the catalog facets for creator, where the A-Z sort should be by last name (per discussion with Metadata WG)
* Forms should split the name into First/Given, Last/Family with a help note about including Middle names with First/Given names - this will require a very lightweight implementation of nested metadata, and I expect that SimpleForms may be a barrier, because the nested First+Last combination should be repeatable. We should expect to spend significant time refactoring specs, too, to support the nested implementation.
* In the context of simple keyword searching, indexing First and Last name separately may mean we lose support for quoted author searches, so we might want to continue to index the creator name as a single field (in both natural and LastName-First order?).
* To support sorting by last name in facets, we'll want to index as `"#{last_name}, #{first_name}"`.

Am I overlooking anything?
