### ISSUE TITLE
Review latest security scans and identify issues for resolution

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#261]
Hailstorm
Burp

Reports stored on ilib.

**Comment by scherztc** [comment]
https://www.owasp.org/index.php/Category:Vulnerability_Scanning_Tools

**Comment by hortongn** [comment]
On the latest Hailstorm scan, the Blind SQL Injection is a false positive.

To run this test, Hailstorm is trying two different queries.  In the first query, it is assigning "1 or 15=15" to the "q" parameter.  In the second query, it is assigning "1 and 13=3" to the "q" parameter.  It's as if the user is putting "1 or 15=15" into the search box.  And then "1 and 13=3" into the search box.

Hailstorm assumes that if those two queries return different results, then Hailstorm has successfully injected SQL into the app.  However, the queries return different results because the first query matches on a work that has the number 1 in the title.  It treats "1 or 15=15" as a boolean search and returns any works that the number 1 or 15=15 in the title.  The second query is treated as a boolean AND.  Since we don't have any works with the number 1 AND 13=3, no results are returned.

I think this comes down to Hailstorm not being smart enough to realize that the "q" parameter is what we use to hold the user's search string and our app is treating the "or" and "and" as boolean logic.  It's just coincidence that we have a work with the number "1" in the title.

**Comment by hortongn** [comment]
Also, Hailstorm probably didn't find an SQL injection in the past because we simply didn't have any works that matched the values it put into the "q" parameter.  We may want to make a habit of wiping QA before each scan so there's a consistent environment for Hailstorm.
