### ISSUE TITLE
Display Best URL for linking to work - Scholar_Use_Cases - Submission 10

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#287]
This should be a DOI if one has been minted for the work from Scholar

**Comment by newmanld** [comment]
@jamesvanmil - I've been adding records this morning to scholar-qa to test my issues.  I'm finding that the alternative link is not working (while I'm logged in) on the show page, even though if manually change the path in the URL that works.  If I cut and paste the show link into my url field this does not work. ??

**Comment by jamesvanmil** [comment]
After some research I wasn't able to find a way to dynamically pull the host URL from the application, so I hard-coded `https://scholar.uc.edu` (see: https://github.com/uclibs/curate_fork/blob/develop/config/locales/sufia.en.yml#L5)

For ordinary links you don't need to do this because you can just use the path, but if you try to display the text that the path generates, you just get "/show/pid". 

This means that the links are expected only to resolve back to the item on the production application.

**Comment by newmanld** [comment]
@jamesvanmil - just realized that qa was not in the displayed link on the show page.  Duh on my part.  But let's write up another issue to figure out how to dynamically pull the host URL and link this issue we are about to close to that new issue -- with a note that if a solution is found we should stop hardcoding this.  Let me know if that makes sense.  Thanks.

**Comment by jamesvanmil** [comment]
+1

**Comment by newmanld** [comment]
@jamesvanmil  - is this relevant?: http://stackoverflow.com/questions/2165665/how-do-i-get-the-current-absolute-url-in-ruby-on-rails

**Comment by hortongn** [comment]
@jamesvanmil I see that you added a line to /config/locales/sufia.en.yml in the Gem, but do we also need to add it to our application in /config/locales/sufia.en.yml?

**Comment by jamesvanmil** [comment]
No - like the changes I made to support the hints for the metadata input, these seem to come in without a local patch.
