### ISSUE TITLE
Create task regularly to run anti-virus software against Fedora and all content

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#346]
Thomas pointed out that there may be some cases (Avatars for Collections) where ClamAV does not run on demand against user uploaded content.  We can
 a) find any such examples and add the virus scan
b) run a scheduled virus scan as a rake task.

**Comment by hortongn** [comment]
Installed ClamAV on the dev Fedora server and manually inserted a mock virus signature into Fedora.  Ran clamscan against the Fedora data directory and it successfully identified the malicious file.

We can set up a cron job to scan Fedora and report to us via email if anything is found.  The trick will be determining how often to scan given that we will eventually have terabytes of data.

**Comment by hortongn** [comment]
scholar-dev.uc.edu is now configureed to update it's virus definitions and run a scan on Fedora content nightly.  Since the dev server doesn't have much content, it's safe to run a scan every night.

Install
1. sudo yum install clamav clamav-devel clamav-db
2. sudo freshclam

root user's crontab (nightly)
/usr/bin/freshclam

tomcat user's crontab (nightly)
/usr/bin/clamscan --recursive --infected --no-summary /usr/local/fedora/data/

Add to puppet scripts

**Comment by hortongn** [comment]
QA's Fedora server already has ClamAV installed.  So I was able to schedule nightly scans of Fedora content.  I'll need to work with Andy to get ClamAV installed on production Fedora.

**Comment by hortongn** [comment]
The following tasks need to be done on the **production** Scholar Fedora server (libhydpfl1) so we can run regular virus scans on content in Fedora.

1. sudo yum install clamav clamav-devel clamav-db
2. sudo freshclam

I've already adjusted the Puppet scripts to install ClamAV on the Fedora boxes.

**Comment by bng44270** [comment]
This is completed on the Fedora production server

**Comment by hortongn** [comment]
Everything checks out.  Thanks @bng44270 !
