### ISSUE TITLE
Export content and re-format in Bag format necessary for APTrust

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#347]
Starting with proof of concept - moving on to actual submission to APTrust.  Work with Nathan Tallman for APTrust specs.

**Comment by newmanld** [comment]
Thomas Scherz @scherztc will provide to Nathan Tallman @ntallman a sample foxml file created by exporting one work and related files from the production, and working with test content on development and sandbox using webgui and fedora command line.

**Comment by jamesvanmil** [comment]
See issue #370 - this implies that the conversion from FOXML to Bag should be round-trippable.

**Comment by jamesvanmil** [comment]
Next steps:

1. Export sample data from QA or DEV for Nathan
1. Settle question of how to export from production - can the web console help with this?

**Comment by scherztc** [comment]
+1

**Comment by scherztc** [comment]
When running the following command  ./fedora-export.sh localhost:8080 <username> <password> DMO info:fedora/fedora-system:FOXML-1.1 archive /tmp http on the QA system we get an error that we don't get on larry.

WARN 15:00:35.901 (PhaseInterceptorChain) Interceptor for {http://fedora-commons.org/2011/07/definitions/types/}FedoraAPIMMTOMService#{http://fedora-commons.org/2011/07/definitions/types/}export has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.

Caused by: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://localhost:8443/fedora/services/managementMTOM: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by scherztc** [comment]
http://www.mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/

I think that this may be a solution.

**Comment by scherztc** [comment]
Other useful commands for testing ssl:

openssl s_client -connect scholar.uc.edu:443 -showcerts

https://www.ssllabs.com/ssltest/analyze.html

**Comment by scherztc** [comment]
I tried testing these in my local vagrant environments, but did not get the initial error.  I am trying to determine if this is a forced https: /  certificate chain / or JAVA and SSL problem.

**Comment by scherztc** [comment]
The long story short here is to run java InstallCert server:1234 to generate a file called jssecacerts. Then, drop this file in ${JAVA_HOME}/lib/security directory.

**Comment by scherztc** [comment]
Installed:  yum install java-1.7.0-openjdk-devel

**Comment by scherztc** [comment]
Completed InstallCert process.  Now getting a 401:  Unauthorized Error.

HTTPException: HTTP response '401: Unauthorized' when communicating with http://localhost:8080/fedora/services/accessMTOM

**Comment by scherztc** [comment]
@scherztc and @ntallman need to come together on content export.  Even if we have to use Dev content.

**Comment by scherztc** [comment]
http://stackoverflow.com/questions/31270327/why-does-my-fedora-admin-sh-findobjects-throw-an-exception

**Comment by scherztc** [comment]
you will also get 401s if the fedora user account doesn't have disk permissions, but that would fail in the admin GUI thing, too

**Comment by scherztc** [comment]
well, fwiw we have a forced ssl setup, but we use the REST api from off-server.
[10:43am] thomas_uc: hmmm.... meaning you run the fedora-export command off-server?
[10:43am] thomas_uc: I will try that.
[10:43am] barmintor: no, the opposite
[10:43am] barmintor: I mean that we run everything off server, but we don't use the SOAP api
[10:44am] barmintor: but I know off-server, SSL, REST export is working
[10:44am] barmintor: so... I assumed it was a user problem

**Comment by scherztc** [comment]
127.0.0.1 - - [13/Oct/2015:11:08:53 -0400] "GET /fedora/management/upload HTTP/1.1" 302 -
127.0.0.1 - - [13/Oct/2015:11:08:53 -0400] "GET /fedora/wsdl HTTP/1.1" 200 241
127.0.0.1 - - [13/Oct/2015:11:08:55 -0400] "GET /fedora/management/upload HTTP/1.1" 302 -
127.0.0.1 - - [13/Oct/2015:11:08:56 -0400] "POST /fedora/services/accessMTOM HTTP/1.1" 401 22
127.0.0.1 - - [13/Oct/2015:11:12:43 -0400] "GET /fedora/management/upload HTTP/1.1" 302 -
127.0.0.1 - - [13/Oct/2015:11:12:43 -0400] "GET /fedora/wsdl HTTP/1.1" 200 241
127.0.0.1 - - [13/Oct/2015:11:12:44 -0400] "GET /fedora/management/upload HTTP/1.1" 302 -
127.0.0.1 - - [13/Oct/2015:11:12:45 -0400] "POST /fedora/services/accessMTOM HTTP/1.1" 401 22

**Comment by scherztc** [comment]
curl -u fedoraAdmin:fedoraAdmin -X POST http://localhost:8080/fedora/objects/new\?namespace\=test

**Comment by scherztc** [comment]
curl -u fedoraAdmin:PASSWORD -X POST http://localhost:8080/fedora/objects/new\?namespace\=test
Fedora: 401

**Comment by scherztc** [comment]
Resolved the 401 problem...  Copy / paste error on password.  Back to certificate problem: 

Caused by: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://localhost:8443/fedora/services/managementMTOM: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by scherztc** [comment]
you might need to install CA cert

**Comment by scherztc** [comment]
barmintor: that's Java being finicky about your SSL cert
[12:36pm] barmintor: you might need to install CA cert
[12:36pm] barmintor: but there is also some nonsense about GoDaddy certs that required a JDK patch

**Comment by scherztc** [comment]
http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html

**Comment by scherztc** [comment]
Discovered a different error message on production:

Exporting fedora-system:ContentModel-3.0 to /tmp/fedora-system_ContentModel-3.0.xml
Exporting fedora-system:FedoraObject-3.0 to /tmp/fedora-system_FedoraObject-3.0.xml
Exporting fedora-system:ServiceDefinition-3.0 to /tmp/fedora-system_ServiceDefinition-3.0.xml
Exporting fedora-system:ServiceDeployment-3.0 to /tmp/fedora-system_ServiceDeployment-3.0.xml
Exporting sufia:05741r680 to /tmp/sufia_05741r680.xml
Exporting sufia:0r967372b to /tmp/sufia_0r967372b.xml
Error  : javax.xml.ws.soap.SOAPFaultException: Authorization Denied Caused by: Authorization Denied Caused by: -bash-4.1$ cd /tmp

**Comment by scherztc** [comment]
We modified the deny-d fedora policy to allow access to soft deleted items from localhost.
We ran into a JAVA HEAP error when trying to export PIDs greater to 250 MB in size.

We are considering other options for export including the REST API:
https://wiki.duraspace.org/display/FEDORA36/REST+API#RESTAPI-export

We will probably have to write a bash script to find all the PIDs and run them through the REST API.

**Comment by scherztc** [comment]
Might need the POSTMAN extension for chrome.

**Comment by newmanld** [comment]
See https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by scherztc** [comment]
Verify if there is any difference between binary files encoded into FOXML (archive) or if the links to files in FOXML (migrate).

Get Nathan involved.

**Comment by ntallman** [comment]
Can you please send me the following exports for the same work:
- FOXML with Base64 encoded bitsreams
- FOXML with paths to bitstreams
- METS with Base64 encoded bitsreams
- METS with paths to bitstreams

**Comment by scherztc** [comment]
Work: https://scholar-dev.uc.edu/works/images/r781wg024

FOXML with Base64 encoded bitsreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg024/export?context=archive
FOXML with paths to bitstreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg024/export?context=migrate
METS with Base64 encoded bitsreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg024/export?format=info:fedora/fedora-system:METSFedoraExt-1.1&context=archive
METS with paths to bitstreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg024/export?format=info:fedora/fedora-system:METSFedoraExt-1.1

File (/attached to Work): https://scholar-dev.uc.edu/works/files/r781wg03d

FOXML with Base64 encoded bitsreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg03d/export?context=archive
FOXML with paths to bitstreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg03d/export?context=migrate
METS with Base64 encoded bitsreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg03d/export?format=info:fedora/fedora-system:METSFedoraExt-1.1&context=archive
METS with paths to bitstreams : https://curate-devdb.uc.edu/fedora/objects/sufia:r781wg03d/export?format=info:fedora/fedora-system:METSFedoraExt-1.1
