### ISSUE TITLE
Dynamically pull application URL for 'perma'-links

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#368]
See discussion on #287

**Comment by jamesvanmil** [comment]
http://stackoverflow.com/questions/2165665/how-do-i-get-the-current-absolute-url-in-ruby-on-rails

**Comment by hortongn** [comment]
@jamesvanmil Back in October we set a line in /config/initializers/curate_config to use a Bamboo variable.  The comment on that line says "Used for constructing permanent URLs."  So maybe you can just reference config.application_root_url instead of a hard coded URL?  See https://github.com/uclibs/scholar_uc/blob/develop/config/initializers/curate_config.rb#L11-L12

**Comment by scherztc** [comment]
Closed #383

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/commit/b418ff235598d334ddb1ba4d43e9804b5a87a6dd
