### ISSUE TITLE
Create New ETD Work type

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#387]
Notre Dame branch for integrating ETD’s into curate:  
https://github.com/ndlib/curate/commits/etd-rebased

**Comment by jamesvanmil** [comment]
Need to add:

* Degree year
* Other committee members

**Comment by jamesvanmil** [comment]
Remaining to-dos:

* Restricting access to creating ETDs
* Fixing some form responsiveness issues
* Upcasing ‘Etd’
* enforcing input on ‘year'

**Comment by newmanld** [comment]
Suggestions:
On Add New Works page - extend description for student works to add a clause such as " (except Electronic Theses and Dissertations)", extend description for ETDs to say "(must be submitted by the UC Graduate School)".  On input form - instead of 'Submit Your ETD' - 'Submit an ETD'?

**Comment by newmanld** [comment]
I wonder if we should tweak the form so that The Graduate School (name to be associated with the account they will use) is not automatically an Author.  Although they can remove themselves as an author, it seems an extra step.  They would still be the owner and would show up on the show page as submitter.  They would still be the editor.  Something we should ask when we demo the form?

**Comment by jamesvanmil** [comment]
+1 on all these - working on some new changes that aren't up on Larry yet

**Comment by jamesvanmil** [comment]
@newmanld here's what happens when we extend that text on the Add New Works page:

<img width="247" alt="screen shot 2016-05-26 at 11 27 04 am" src="https://cloud.githubusercontent.com/assets/2651187/15579963/dbe612c8-2334-11e6-99db-78c36842a5eb.png">

Since they know what ETDs are (and no one else will see this), how about changing to:

<img width="224" alt="screen shot 2016-05-26 at 11 29 26 am" src="https://cloud.githubusercontent.com/assets/2651187/15580038/1faabea0-2335-11e6-808f-51503f5c8ac1.png">

**Comment by newmanld** [comment]
+1 to abbreviated text!

**Comment by jamesvanmil** [comment]
Additional changes needed:

* Suppress ETD manager from catalog results
* Add legacy college names to form dropdown

**Comment by newmanld** [comment]
James – if you’re referring to the People (profiles) tab on catalog results, I had assumed that we would not suppress the ETD manager from catalog results – that the Grad School’s user profile would display like any other, as the email address is the same one they use for public comment, so having their phone number and email address publicly associated with their name (The Graduate School) doesn’t seem problematic.   But maybe ask the Grad School in our meeting today?

**Comment by jamesvanmil** [comment]
Sounds good - I had removed the "Submitter" attribute from the ETD work display, too - let's ask about that, too.
