### ISSUE TITLE
Sort options not being retained with next button on catalog browse of Works

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#542]
I just discovered what seems a clear bug.  If I am browsing the catalog limited to works, I have a drop down list of sort options.  If I choose a sort option other than the default relevance, and apply that option with the 'update' button, this sort order is subsequently lost when I page forward with the Next button - the order returns to relevance.

The above behavior occurs when I am not logged in.  If I log in with my shibboleth identity on production, or non-shibboleth login on our sandbox, I am unable to change the sort even on the first page - the update button returns me to a relevance sort.  I'm assuming this is the same bug behaving differently - but if not, separate as two bugs in our issues.

**Comment by hortongn** [comment]
Interesting.  I wonder if any of our Hailstorm fixes inadvertently caused this.  We filter several parameters that handle sort and pagination. When we tackle this I suggest we spin up an older, pre-Hailstorm version of Scholar and see if the bug is still there.  If it's not, then it's pretty clear we broke something.

**Comment by newmanld** [comment]
Vanilla Curate is up but without any works yet - good place to check?

**Comment by newmanld** [comment]
I was able to manually force a different sort on page 2 – for example in this case by Date Modified  - by adding this in the URL, after catalog? And before &f%5Bgeneric_type_sim…

utf8=✓&sort=desc_metadata__date_modified_dtsi+asc&per_page=10&

So my URL became:
https://scholar.uc.edu/catalog?utf8=%E2%9C%93&sort=desc_metadata__date_modified_dtsi+asc&per_page=10&f%5Bgeneric_type_sim%5D%5B%5D=Work&page=2

Have not tried while logged in.

**Comment by hortongn** [comment]
This is quite possibly the result of code implemented in https://github.com/uclibs/curate_fork/blob/develop/app/helpers/params_helper.rb

A good way to tell is to check out a curate_fork commit prior to 12/1/2014 and see if the problem is gone from the test app (e.g. git checkout d4cd71a17d144df4db83c49c2e5a268705ce8021).

There may be some sort parameters that need to be added to safe_params.

**Comment by 13miciunasl** [comment]
Using the commit Glen mentioned I verified that the sort params DO persist after paging forward or back. It works the same logged in or not. It appears Glen is probably right about adding some parameters to the safe_params hash
