### ISSUE TITLE
Investigate Article Stop list in our SOLR environment and Implement where applicable.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#561]

**Comment by jamesvanmil** [comment]
Problems with sorting within facet fields are not addressable without actually changing the content of the field that's being faceted on. We can copy the facet to a new field, removing only leading articles and faceting on that field, preserving the entire field for display elsewhere.

If we want to additional results sorting (by title, author, etc), we'd need to take a similar approach, but use a more aggressive filter to implement everything we'd need for alphanumeric sorting.

For collections, it's probably realistic to sort objects by title in the view within the helper method that retrieves them, because the collections page doesn't appear to use Blacklight.

**Comment by jamesvanmil** [comment]
@newmanld Did you want us to go ahead and address the problem in the facets now, or create new issues to tackle later?

**Comment by jamesvanmil** [comment]
Replaced by issues #572 and #573
