### ISSUE TITLE
Hailstorm cross-site scripting vulnerability

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc#567]
We have a new HARM score.  It’s a cross site scripting vulnerability in Set C for the collection title.  Hailstorm is injecting "><script>alert(14497103.4347)</script>;// which we've not seen before. 

The vulnerability was reported in Hailstorm Set C which ran 12/9/15 at 8:19 pm.  The link below should take you directly to the vulnerability

https://hailstorm.uc.edu/Hailstorm.ARC/jobs/VulnerabilityListView.aspx?jrid=6d2d54b4-ea78-4868-8cde-b42ab36fa18f

**Comment by crowesn** [comment]
https://github.com/rails/rails-html-sanitizer#railshtmltargetscrubber

**Comment by crowesn** [comment]
Resolves https://github.com/uclibs/scholar_uc/issues/567

**Comment by scherztc** [comment]
@jamesvanmil @crowesn 

We have already explored middleware sanitization in https://github.com/uclibs/scholar_uc/blob/develop/app/middleware/utf8_sanitizer.rb rather than the application_controller.rb.  

We could rename this utf8_sanitizer.rb to just sanitizer.rb and include a few more checks.

Take a look at the linked file and let's chat.

**Comment by hortongn** [comment]
I haven't looked at it very closely, but this gem might help for scrubbing script tags in parameters.
https://github.com/rails/rails-html-sanitizer
