### ISSUE TITLE
Upon registration send welcome email to user

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#609]
When a new user registers on Scholar, the content of the appropriate Welcome page (faculty/staff vs. student) should also be sent to the user as an email.

**Comment by lawhorkl** [comment]
I've pushed a branch up to curate that adds a simple mailer for this.

Just one question, I'm not exactly sure how I would test that the email sends, I believe I have it working but when I test it as is, I'm getting a connection refused error on port 25, I'm assuming because SMTP isn't set up on development. Any ideas?

**Comment by newmanld** [comment]
I'm re-opening this issue since we realized the email wasn't being triggered for Shibboleth users.  And per @ntallman the email should be slightly refactored to say 'this email' instead of 'this page' - @lawhorkl I will work with you on this.

**Comment by newmanld** [comment]
Also, let's be sure that the Welcome email message going to students is the custom welcome message for students.

**Comment by newmanld** [comment]
Also, let's be sure that the Welcome email message going to students is the custom welcome message for students.

**Comment by lawhorkl** [comment]
@ntallman @newmanld I pushed up a commit that adds support for the student email. If you guys can look over and give me feedback of the email content for students, it would be appreciated!

https://github.com/uclibs/curate/compare/feature/%23609-welcome-email-on-waiving-welcome

**Comment by lawhorkl** [comment]
closed with uclibs/curate#34
