### ISSUE TITLE
Upgrade to Fedora 3.8.x

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#643]
Per this thread in Hydra-Tech.   https://groups.google.com/forum/#!topic/hydra-tech/RuFv96JJX3I

The thread reports the possibility of data loss in 3.7.  Ben sums it up: 
       Forgive the soapboxing, but I really cannot stress enough the importance of getting onto 3.8.1. It requires JDK 8, that's probably your biggest hurdle.

Description of the 3.7.x bug:
          This is might be due to running parallel updates to objects on Fedora < 3.8.1, where an object locking flaw could lead to phantom DS updates when multiple updates to the same datastream were being processed simultaneously. 

For more detail see: https://jira.duraspace.org/browse/FCREPO-1284

**Comment by hortongn** [comment]
This gets kinda confusing.  In our local environments we have our app's Gemfile pinned to jettywrapper 1.8.3.  Jettywrapper 1.8.3 locks us to hydra-jetty 7.0.0.  Hydra-jetty 7.0.0 uses Fedora 3.7.0.  So that's what we are running locally (and on Larry).

If we move to the next version of Jettywrapper (2.0.0) that throws us to a hydra-jetty that has Fedora 4.  So we don't want to do that.  There doesn't seem to be an easy way for us to use Fedora 3.8.1 in our local environments.  However, I don't think we need to worry about this bug in our local environments.

None of the above applies in our server environments where we are using Tomcat instead of Jetty.  We should be able to upgrade Fedora to 3.8.1 and upgrade to Java 8 without much of an issue, but it needs to be tested, of course.  Ideally these updates should all be integrated into our Puppet scripts and we should start with scholar-dev and run all automated and manual tests.

**Comment by hortongn** [comment]
Local vagrant environment our web and data servers is up and running.  Next steps:
* upgrade Java to version 8.  Verify all is well.
* upgrade Fedora to 3.8.1.  Verify all is well.
* Get the Fedora 3.8.1 install into Puppet.
* deploy to dev, qa, production

**Comment by hortongn** [comment]
Using Vagrant I've verified that the Puppet changes I made properly recreate our Fedora environment with Java 8 and Fedora 3.8.1.  I ran our app and gem tests and all of them pass under 3.8.1.  So no other changes appear to be needed for this upgrade.

Next step is to do the fedora upgrade on scholar-dev and test.

**Comment by hortongn** [comment]
When Fedora is upgraded on dev/qa/production, care needs to be taken to preserve config files, logs, XAMCL, policies, and data.  We need an inventory of files we don't want to overwrite.

**Comment by hortongn** [comment]
The Fedora 3.8.1 upgrade is complete on scholar-dev.  I’ll do some testing and will move on to upgrading scholar-qa.  Since all of the files involved with the upgrade are owned by the tomcat user, we should be able to do this upgrade ourselves on production without help from UCit.  We will need to submit a change request.

**Comment by hortongn** [comment]
The Fedora 3.8.1 upgrade on scholar-qa is complete.

**Comment by hortongn** [comment]
I've Asked Andy to find time the week of May 9 to do the Java 8 upgrade on production Fedora.  We can then handle the actual Fedora upgrade ourselves.

**Comment by hortongn** [comment]
Steps to upgrade java prior to Fedora upgrade:
* sudo yum remove jdk.x86_64
* sudo yum install java-1.8.0-openjdk-devel
* /usr/sbin/alternatives --config java
* sudo /usr/sbin/alternatives --config javac

**Comment by hortongn** [comment]
I've verified that Java has been upgraded to version 8 on the production Fedora server.  Next step is for us to do the actual Fedora 3.8.1 upgrade (change request needed).  The steps for the upgrade are below (verified on QA).

### Prep
* sudo service tomcat stop
* sudo su - tomcat
* sftp new 381 tar balls to /usr/local/tomcat

### Backup 3.7.1 stuff
- cd /usr/local
- tar -czf ~/usr-local-fedora371.tar.gz fedora
- tar -czf ~/usr-local-tomcat371.tar.gz tomcat
- cp /usr/local/fedora/server/config/fedora.fcfg* /tmp
- cp /usr/local/fedora/server/config/fedora-users.xml /tmp
- cp /usr/local/fedora/install/install.properties /tmp
- cp -rp /usr/local/fedora/server/logs /tmp/logs
- cp /usr/local/tomcat/webapps/fedora/WEB-INF/applicationContext.xml /tmp

### Copy new fedora files
- cd /usr/local/fedora
- rm -rf *
- tar -xzf /usr/local/tomcat/usr-local-fedora381.tar.gz

### Copy new tomcat files
- cd /usr/local/tomcat/webapps
- rm fedora.war
- rm -rf fedora
- tar -xzf /usr/local/tomcat/usr-local-tomcat381.tar.gz

### Copy config and log files
- cp /tmp/fedora.fcfg* /usr/local/fedora/server/config/
- cp /tmp/fedora-users.xml /usr/local/fedora/server/config/
- cp /tmp/install.properties /usr/local/fedora/install/
- cp /tmp/applicationContext.xml /usr/local/tomcat/webapps/fedora/WEB-INF/
- rm /usr/local/fedora/server/logs/fedora.log
- cp -rp /tmp/logs /usr/local/fedora/server/logs/logs-3.7.1

### Edit fedora.fcfg and change the following value
`<param name="XACML-COMBINING-ALGORITHM" value="org.jboss.security.xacml.sunxacml.combine.OrderedDenyOverridesPolicyAlg"/>`

### Finish
- make sure everything is owned by tomcat:tomcat
- exit the tomcat user
- sudo service tomcat start

**Comment by hortongn** [comment]
The upgrade is complete
