### ISSUE TITLE
Display unique information beside a name in a select list, when assigning rights

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#650]
As a submitter, if I am selecting another submitter to be a member of a Group, to be an Editor, or to be my Delegate, or any other function that uses the type ahead feature to select among existing users for the purpose of granting rights, I want to be able to distinguish between the theoretical possibility of identical names. (Feedback from Scholar Camp 2016-03-03)

Done looks like:
In a selection list, I see:  Firstname Lastname (email address)

**Comment by newmanld** [comment]
Alternative solution: Display email address instead of name in a selection list.

**Comment by jamesvanmil** [comment]
We should also enable searchability for any additional information we are displaying, e.g., the 6+2

**Comment by lawhorkl** [comment]
@13miciunasl i was looking at it and the display issues with the checkboxes are present on develop for me, so it was an existing issue.

We might have to look at refactoring the template to really solve it

**Comment by jamesvanmil** [comment]
I support this approach, especially because the changes aren't introducing new issues - I think we need to make some limited UI changes within this issue, because it's resulting in much more text being displayed. The horizontal scroll within the field, plus a slightly smaller text size for these fields, would go a long way.
