### ISSUE TITLE
Delegate is exposed to public as "Depositor" on file show page

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc#766]
As a: user
I want to: suppress the name/contact of my delegate
So that: no one can tell that my delegate uploaded the file and not me

As a: repository manager
I want to: know exactly who submitted a file, even if it's a delegate
So that: I know who to contact if there was a problem

**Comment by jamesvanmil** [comment]
@ntallman for avoidance of doubt, do these stories hold if `s/delegate/editor/`?

**Comment by ntallman** [comment]
@jamesvanmil: No for the first; yes for the second.

**Comment by jamesvanmil** [comment]
So if an added editor uploads a file, you prefer that they should be noted as the owner of that file? (spoiler alert: this isn't currently the case)

**Comment by ntallman** [comment]
If an added editor uploads a file, I think the editor should be displayed as the depositor. Depositor is what displays in Scholar, is that what you are referring to when you say "noted as the owner of that file?

**Comment by jamesvanmil** [comment]
Let's chat about this in meatspace.

**Comment by jamesvanmil** [comment]
Chatted with @ntallman - we agree that delegates should not be exposed as file depositors. Also, because it would require additional administrative metadata to be able to expose added editors as file depositors, we should not seek to expose that information either.

Further, because file ownership is kept in sync with work ownership, there is no added value is exposing ownership information, because we do that at the work level.

Recommend for this file attribute to be removed from the file show page.

**Comment by scherztc** [comment]
@jamesvanmil :  We have a submitter and creator in the work show page.  Does this meet this need?

**Comment by scherztc** [comment]
Product owners chose another direction.
