### ISSUE TITLE
IIIF display not working on dev

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#791]
IIIF display is failing for works on Dev but not QA and not production

**Comment by scherztc** [comment]
I am still having problems with LORIS on the DEV server.  I have the 6.7.2 version of ImageMagick installed.  The problem is with the LORIS server itself.  It keeps giving me the 500 error, rather than the about page.  I think it can wait a week, but if anyone else wants to look at it.  Here is the installation and configuration gist:  https://gist.github.com/scherztc/0aa5471084104f1cf555.

**Comment by scherztc** [comment]
Use http://curate-devdb.uc.edu:8080 in /etc/loris2/loris2.conf.
