### ISSUE TITLE
Auto-populate creator on new works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#880]
As Lastname, Firstname

**Comment by jamesvanmil** [comment]
Depends on #879

**Comment by scherztc** [comment]
As a content submitter/owner. I want the first creator metadata field to default to the submitter's name (or in the case of a delegate/proxy, the delegator/owner's name), as it does in Scholar 2.x. As in Scholar 2.x, I can override this with another value, if I am not the Creator. So that: My name is entered accurately and consistently and I do not have to re-type it, for the majority of cases where I will submit works where I am the creator.

**Comment by crowesn** [comment]
https://github.com/psu-stewardship/scholarsphere/pull/123/files

**Comment by scherztc** [comment]
Size: 4
