### ISSUE TITLE
Document the scope of proxy abilities in Sufia

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#890]

**Comment by jamesvanmil** [comment]
Follow-up issue will be to determine what we would like to change.

**Comment by scherztc** [comment]
Size:  2

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/blob/112394a3deb9f56c52616e829e04d0d4ebee2907/spec/features/proxy_spec.rb

**Comment by newmanld** [comment]
Behavior today of Scholar 3.x with Sufia 7.x:

A proxy cannot edit a work that the owner submitted before they made them a proxy.

After a proxy submits a work on the owner's behalf, it shows up on the Dashboard for the owner under 'My Works.'  It shows up on the Dashboard for the Proxy under 'Works Shared With Me'.  Both the editor and the proxy can edit this work.

When an owner submits another work (after they have established a proxy), the proxy cannot edit that new work.  So it appears that a proxy can only edit works that they have submitted on the owner's behalf.

There is no help statement about Proxies on the Dashboard (where an owner assigns a proxy.)  There is a user notification generated for both the owner and the proxy.  For the proxy: "<owner email> has assigned you as a proxy depositor".  For the owner: "You have assigned <proxy email> as a proxy depositor."

The owner sees a list of their Proxies on the Dashboard, under Manage Proxies.  I don't see a similar area to list who has made me their proxy - so if the notification scrolls off, I could forget that I am someone's proxy.

On the submission form, the choice to submit on behalf of 'Yourself' or the owner, is in the lower right.  On Scholar 2.x it is at the top of the form.  It defaults to 'Yourself'.  This may not be visible enough to avoid a proxy submitting for themselves, rather than the owner?

**Comment by newmanld** [comment]
Unanticipated differences - I will write up new issues:
If I remove someone as my proxy, they can still edit the work they submitted.  (They can no longer create new works on my behalf.)  It appeared that as owner, to revoke the former proxy's edit access to the works they submitted, I would have to edit the work, go to Share, and remove the former Proxy as an editor.  I would have to do this on each work.  However, I did this and the proxy still had edit access to the work that they had formerly created - until they edited the work and saved it - then they lost their edit access.  So this appears to be two bugs.  I will write up.

There is also no notification generated when a proxy is removed, for me as the owner that I removed someone as my proxy, or for the proxy that they have been removed.

**Comment by newmanld** [comment]
Also worth pointing out -
When a proxy submits a work on behalf of an owner, the owner sees an entry on their dashboard that says that they proxy has transferred the work to them.  This may leverage the same code that is behind the option any submitter has on the dashboard to Transfer Ownership of a Work.  So two actions take place when the proxy completes a submission on behalf of an owner: the work is transferred to the owner, and the proxy is made an editor on the work.
